fruits=[]
fruit1=input("Enter the fruitname")
fruits.insert(0,fruit1)
fruit2=input("Enter the fruitname")
fruits.insert(1,fruit2)
# fruit3=input("Enter the fruitname")
# fruits.append(fruit3)
# fruit4=input("Enter the fruitname")
# fruits.append(fruit4)
# fruit5=input("Enter the fruitname")
# fruits.append(fruit5)
# fruit6=input("Enter the fruitname")
# fruits.append(fruit6)
# fruit7=input("Enter the fruitname")
# fruits.append(fruit7)
print(fruits)